stages:
  - test

variables:
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"

default:
  image:
    name: $CI_REGISTRY/images/goreleaser:stable
    entrypoint: [""]

test:
  stage: test
  script:
    - gotestsum --junitfile report.xml --format testname -- -coverprofile=coverage.out -covermode=count
    - gocover-cobertura < coverage.out > coverage.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
