stages:
  - test
  - release

variables:
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"

default:
  image:
    name: $CI_REGISTRY/images/goreleaser:stable
    entrypoint: [""]

test:
  stage: test
  script:
    - gotestsum --junitfile report.xml --format testname -- -coverprofile=coverage.out -covermode=count ./...
    - gocover-cobertura < coverage.out > coverage.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    # Provide so that goreleaser uses the job token
    GITLAB_TOKEN: $CI_JOB_TOKEN
  script:
    - goreleaser release --clean
